### ISSUE TITLE
Building the latest Adjust SDK with Xcode 7.3.1

### ISSUE THREAD

**Issue by superbybot** [adjust/ios_sdk#305]
I'm having a xcode linker error building Adjust SDK 4.11.2 with Xcode 7.3.1 and here's the log of the error.
```
  "_kSecAttrAccessGroupToken", referenced from:
      -[ADJActivityState assignUuid:] in AdjustSdk(ADJActivityState.o)
      -[ADJKeychain setValue:forKeychainKey:inService:] in AdjustSdk(ADJKeychain.o)
      -[ADJKeychain keychainItemForKeyNew:service:] in AdjustSdk(ADJKeychain.o)
      -[ADJKeychain setValueWithStatus:forKeychainKey:inService:] in AdjustSdk(ADJKeychain.o)
      -[ADJKeychain wasWritingSuccessful:forKeychainKey:inService:] in AdjustSdk(ADJKeychain.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I saw this thread [(https://github.com/adjust/ios_sdk/issues/289)] suggesting to use Xcode 8 to resolve the problem, but that wont be an option for us since we would be supporting devices up to iPhone 4s. So is there any other solution to the problem? (Maybe downgrade our Adjust SDK version?)

Thanks!

Regards,
Byron

**Comment by uerceg** [comment]
Hi @superbybot

Current iOS SDK version contains things for which iOS 10.0 SDK is needed to compile it. In upcoming 4.12.0 release of Adjust SDK, we're planning to change that so that this is not a constrain anymore. Work on 4.12.0 is in progress, no precise ETA at this moment though.

What you can try in the meantime is to add iOS 10.0 SDK support to your Xcode 7. Seems doable from what I see in here: https://stackoverflow.com/questions/37945376/use-xcode-7-with-ios-10 and also here's comment mentioning your Xcode version: https://stackoverflow.com/a/39027105/1498352

Downgrading Adjust SDK version can be temporary solution as well if you have all features you need inside 4.11.0 or 4.11.0 versions of Adjust Adobe AIR SDK.

Lemme know if you need any further help.

Cheers

**Comment by uerceg** [comment]
Sorry, I mentioned Adobe AIR SDK since I saw your comment in there first, just noticed you have opened the issue in here.

**Comment by superbybot** [comment]
@uerceg 

Thanks for the quick reply! We'll probably go with the stackoverflow solution for now, as I don't think downgrading the Adjust SDK is an option for us. 

Thanks!

Regards,
Byron
