### ISSUE TITLE
Cannot submit build with v4.12.1 dynamic framework.

### ISSUE THREAD

**Issue by JienLee** [adjust/ios_sdk#319]
xcode : 9.2
macOS : 10.13.2
Adjust framework version : 4.12.1

When I used v4.11.4 DynamicWithoutSimulator.framework is success submit. But when CI tool run test build, that build is failed.  So I changed dynamic.framework lastest version(4.12.1). This version CI tool test and Release build is succeed. But when execute vaildate the .ipa file in Organziner tool, that result noticed fail issue.
I cannot submit build to App Store.

I've try clean, re-build, mac restart, etc..

Any idea how to fix this problem?

![171227_submit_fail](https://user-images.githubusercontent.com/31241214/34369452-29f9168e-eaff-11e7-80ca-37d743a58d2e.png)

**Comment by uerceg** [comment]
@JienLee I have added that target we stopped to ship in v4.12.1 releases page. Can you give it a try and let me know if it worked for you?

**Comment by JienLee** [comment]
@uerceg 
v4.12.1 - dynamicNoSimulator.framework is pass though the validate.

But it seem to not working on simulator. 

When applies that framework to my app and then running CI tool the test, it can't pass the test.


- test error is
  - Undefined symbols for architecture x86_64
  - Symbol: _OBJC_CLASS_$_ADJConfig
  - ld: symbol(s) not found for architecture x86_64


**But I need a framework, when CI tool testing my app, passing the test on both environment. (test(simulator) and real device)**

Because I using the CircleCI tool, need to work on either a test and release environment. 

Please some advice, how to use dynamic.framework on either a test and release environment.

**Comment by uerceg** [comment]
@JienLee 

Well, that's the thing. `AdjustSdkDynamic.framework.zip` contains dynamic framework which contains **all** architectures supported, including those for simulator (i386 and x86_64). `AdjustSdkDynamicWithoutSimulator.framework.zip` doesn't contain simulator architectures. Seems like Apple complains about existence of simulator architectures inside of your app binary before submitting it to the App Store (your initial error), but if you use our framework w/o simulator targets in it, then not being able to run it on simulator is the result (your current problem).

These issues are elaborated a bit more in here: https://stackoverflow.com/questions/30547283/submit-to-app-store-issues-unsupported-architecture-x86/36624921 and https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive.

So you might, for example, use our dynamic framework with all the targets for your CI tool and submit your app with dynamic framework without simulator targets (they are the same, just i386 and x86_64 stripped from the later one). Or use framework with all the targets inside and handle architecture stripping with scripts like suggested in stackoverflow solutions. Or if dynamic framework is not a must in your requirements, try using static one, or adding our SDK through Cocoapods, for example.

**Comment by JienLee** [comment]
@uerceg Thankyou for your advice.
I tried to use cocoapods, but it works fail.

Cocoapods try to this line.
pod 'Adjust', '~> 4.12.1'
**or** 
pod 'Adjust', :git => 'https://github.com/adjust/ios_sdk.git', :tag => 'v4.12.1'

When use the Cocoapods, it generate different issue.
This issue is the reason of not used cocoapods to import adjust.sdk.
And that is why I using Dynamic.framework.

![adjust](https://user-images.githubusercontent.com/31241214/34374579-23c72172-eb25-11e7-9c70-00a8d1dd8b89.png)

**Comment by uerceg** [comment]
Ah, you are building iOS app extension. Since Cocoapods are pretty much adding SDK under the surface via source, then I guess this is not the right way to go, since we still need to do some adjustments for App Extensions.

Is this option with using different dynamic framework builds doable for you? Or this option in which you simply strip not wanted architectures with a script before submitting your app to the store?

**Comment by JienLee** [comment]
That error message is noticed when simulator building. 

Attempt to use 'Run script', but I still in problem.
I try hard to right the 'Run script'.

**Comment by uerceg** [comment]
Awesome. Sorry for delay in reply, didn't notice that you have edited your comment. Glad it worked. 👍 Cheers.
