### ISSUE TITLE
Linking problem with SDK 4.6.0 and iOS Simulator in XCode 6.4

### ISSUE THREAD

**Issue by gtino** [adjust/ios_sdk#187]
Compiling for the simulator with XCode 6.4 does not seem to work with SDK 4.6.0 - We used to have version 4.0.5 of the SDK and everything worked great, but I bet that something related to bitcode is breaking simulator builds for XCode 6.4 in the latest SDK. The linker fails with 50+ duplicate symbols:

`[...]
duplicate symbol _llvm.cmdline in:
    /Users/giorgio.tino/Development/GREE/hc-client/hc-core/Libraries/AdjustSdk.framework/AdjustSdk(ADJTimerCycle.o)
    /Users/giorgio.tino/Development/GREE/hc-client/hc-core/Libraries/AdjustSdk.framework/AdjustSdk(ADJEventFailure.o)
duplicate symbol _llvm.embedded.module in:
    /Users/giorgio.tino/Development/GREE/hc-client/hc-core/Libraries/AdjustSdk.framework/AdjustSdk(ADJTimerCycle.o)
    /Users/giorgio.tino/Development/GREE/hc-client/hc-core/Libraries/AdjustSdk.framework/AdjustSdk(ADJEventFailure.o)
ld: 50 duplicate symbols for architecture i386`

It works in XCode 7 (any kind of builds), and it builds for devices and apple store for XCode 6.4, but these errors appear for debug simulator builds for XCode 6.4

Any clue?

**Comment by uerceg** [comment]
Hi @gtino 

Are you using our SKD as framework to add it to your app and if yes, which one from here https://github.com/adjust/ios_sdk/releases/tag/v4.6.0 ?

If you are using static framework, it comes with bitcode support by default, but we also started to add our static framework version w/o bitcode support in releases page as well.

For me it seems like bitcode issue as well, so you might try our framework w/o bitcode support and see if that fixes your issues in simulator.

Let me know if that worked for you.

Cheers

**Comment by gtino** [comment]
Hi @uerceg 

thanks for the quick reply. I am using your SDK as a Framework, and I have now downloaded the one without bitcode. This solved the problem of the 50+ duplicate symbols, but now I have a new problem:

ld: framework not found ModelIO for architecture i386

I think that ModelIO.framework is part of the SDK shipped with XCode7, so it cannot be found in XCode6. I guess that AdjustSdkStaticNoBitcode.framework.zip framework was build with XCode 7, ModelIO.framework was included (even if not needed, I suppose) thus I cannot use the framework  in Xcode 6, even if the Adjust framework has bitcode disabled...

Am I correct? If so, is there  way to get an XCode 6 compatible framework without having to rebuild it using your source code? I'd prefer to use an official build if possible...

**Comment by nonelse** [comment]
Hi.
Our SDK does not use ModelIO framework. We compile the libraries with the current stable version and try to maintain iOS compatibility to a reasonable version. Besides the different framework we already release, it's also possible to get our SDK through CocoaPods and Carthage. 

Still, in our perspective, the source is the official build. The apps that we test with, link the source directly and the guide also uses the source as the default option. It's the easiest way of guaranteeing compatibility with any Xcode/architecture/iOS configuration.

Cheers.

**Comment by uerceg** [comment]
@gtino Any update on this issue?

**Comment by uerceg** [comment]
Closing this issue due to inactivity. Feel free to reopen it if the issue still occurs.
